package api

import "net/http"

func (s *Server) dashboard(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	_, _ = w.Write([]byte(openworkerDashboardHTML))
}

const openworkerDashboardHTML = `<!doctype html>
<html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>OpenWorker 工作總控</title>
<style>
body{font-family:system-ui,-apple-system,"Segoe UI",sans-serif;margin:0;background:#111827;color:#e5e7eb}header{padding:16px 20px;background:#0b1220;position:sticky;top:0;z-index:3}h1{font-size:20px;margin:0 0 10px}.bar,.actions,.slotbar{display:flex;gap:8px;flex-wrap:wrap}input,select,button{background:#1f2937;color:#e5e7eb;border:1px solid #374151;border-radius:7px;padding:8px}button{cursor:pointer}.danger{border-color:#7f1d1d}.retry{border-color:#92400e}main{padding:16px}.meta{color:#9ca3af;margin:10px 0}.grid{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(360px,1fr);gap:12px}.panel{background:#172033;border:1px solid #27344a;border-radius:10px;overflow:hidden}.detail-head{padding:10px 12px;border-bottom:1px solid #27344a}.slotbar{margin-bottom:12px}.slot{min-width:180px;text-align:left}.slot.active{border-color:#60a5fa}.slot .n{font-size:17px;font-weight:700}.slot .ok{color:#34d399}.slot .bad{color:#fb7185}table{width:100%;border-collapse:collapse;font-size:13px}th,td{padding:8px;border-bottom:1px solid #27344a;text-align:left;vertical-align:top}tr:hover{background:#1d2940}.status{font-weight:700}.running,.starting{color:#fbbf24}.succeeded{color:#34d399}.failed,.timed_out,.cancelled{color:#fb7185}.queued_local,.accepted{color:#60a5fa}.small{font-size:12px;color:#9ca3af}.tabs{display:flex;gap:4px;padding:8px 10px;border-bottom:1px solid #27344a}.tab.active{border-color:#60a5fa}.pane{padding:10px;max-height:72vh;overflow:auto}.artifact{padding:8px 0;border-bottom:1px solid #27344a}.artifact b{word-break:break-all}.hash{font-family:monospace;font-size:11px;color:#9ca3af;word-break:break-all}pre{white-space:pre-wrap;word-break:break-word;margin:0;font-size:12px}.hidden{display:none}@media(max-width:950px){.grid{grid-template-columns:1fr}.slot{min-width:140px}}
</style></head>
<body><header><h1>OpenWorker 工作總控</h1><div class="bar"><input id="filter" placeholder="篩選 case / job / dispatch / command" value="case0005"><select id="status"><option value="">全部狀態</option><option>queued_local</option><option>starting</option><option>running</option><option>succeeded</option><option>failed</option><option>timed_out</option><option>cancelled</option></select><button onclick="clearSlotFilter()">全部 Slot</button><button onclick="loadAll()">重新整理</button><label class="small"><input type="checkbox" id="auto" checked> 3 秒自動更新</label></div></header>
<main><div class="meta" id="meta">載入中…</div><div id="slots" class="slotbar"></div><div class="grid"><div class="panel"><table><thead><tr><th>狀態</th><th>Job / Work</th><th>Slot/PID</th><th>時間</th><th>成果</th></tr></thead><tbody id="jobs"></tbody></table></div><div class="panel"><div class="detail-head"><div class="actions"><button class="retry" onclick="jobAction('retry')">重試</button><button class="danger" onclick="jobAction('cancel')">取消</button></div></div><div class="tabs"><button id="tSummary" class="tab active" onclick="tab('summary')">工作記錄</button><button id="tEvents" class="tab" onclick="tab('events')">Events</button><button id="tArtifacts" class="tab" onclick="tab('artifacts')">成果</button></div><div class="pane"><div id="summary">點選工作查看記錄。</div><pre id="events" class="hidden"></pre><div id="artifacts" class="hidden"></div></div></div></div></main>
<script>
let allJobs=[],slotData=[],selected='',slotFilter=0,detailCache=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function showTime(v){if(!v)return '';try{return new Date(v).toLocaleString()}catch{return v}}
function bytes(n){n=Number(n||0);if(n<1024)return n+' B';if(n<1048576)return (n/1024).toFixed(1)+' KB';if(n<1073741824)return (n/1048576).toFixed(1)+' MB';return (n/1073741824).toFixed(2)+' GB'}
async function loadAll(){try{const [jr,sr]=await Promise.all([fetch('/v1/jobs?limit=500',{cache:'no-store'}),fetch('/v1/slots?limit=500',{cache:'no-store'})]);const j=await jr.json(),s=await sr.json();allJobs=j.jobs||[];slotData=s.slots||[];document.getElementById('meta').textContent='OpenWorker durable jobs: '+allJobs.length+' ｜ '+new Date().toLocaleString();renderSlots();renderJobs();if(selected)loadDetail(selected)}catch(e){document.getElementById('meta').textContent='讀取失敗: '+e}}
function renderSlots(){document.getElementById('slots').innerHTML=slotData.map(s=>{const cur=s.current;return '<button class="slot '+(slotFilter===s.slot?'active':'')+'" onclick="setSlot('+s.slot+')"><div class="n">Slot '+s.slot+(cur?' · '+esc(cur.status):' · idle')+'</div><div class="small">'+(cur?esc(cur.job_id):'目前沒有工作')+'</div><div class="small"><span class="ok">成功 '+s.succeeded+'</span> ｜ <span class="bad">失敗 '+s.failed+'</span> ｜ 共 '+s.total+'</div></button>'}).join('')}
function setSlot(n){slotFilter=n;renderSlots();renderJobs()}function clearSlotFilter(){slotFilter=0;renderSlots();renderJobs()}
function visibleJobs(){const q=document.getElementById('filter').value.toLowerCase(),st=document.getElementById('status').value;return allJobs.filter(x=>(!slotFilter||x.agent_slot===slotFilter)&&(!st||x.status===st)&&(!q||JSON.stringify(x).toLowerCase().includes(q)))}
function renderJobs(){const rows=visibleJobs();document.getElementById('jobs').innerHTML=rows.map(x=>'<tr data-job="'+esc(x.job_id)+'"><td class="status '+esc(x.status)+'">'+esc(x.status)+'</td><td><b>'+esc(x.job_id)+'</b><div class="small">'+esc(x.dispatch_id||'')+'</div><div class="small">'+esc(x.command||'')+'</div></td><td>slot '+esc(x.agent_slot||'-')+'<br>pid '+esc(x.pid||'-')+'</td><td>'+esc(showTime(x.started_at||x.accepted_at||x.created_at))+'<br><span class="small">'+esc(showTime(x.finished_at))+'</span></td><td><button onclick="event.stopPropagation();loadDetail(\''+esc(x.job_id)+'\',\'artifacts\')">查看成果</button></td></tr>').join('')||'<tr><td colspan="5">沒有符合條件的工作</td></tr>';document.querySelectorAll('tr[data-job]').forEach(tr=>tr.onclick=()=>loadDetail(tr.dataset.job,'summary'))}
async function loadDetail(id,openTab){selected=id;try{const [jr,er,ar]=await Promise.all([fetch('/v1/jobs/'+encodeURIComponent(id),{cache:'no-store'}),fetch('/v1/jobs/'+encodeURIComponent(id)+'/events?limit=500',{cache:'no-store'}),fetch('/v1/jobs/'+encodeURIComponent(id)+'/artifacts?limit=200',{cache:'no-store'})]);const job=await jr.json(),events=await er.json(),arts=await ar.json();detailCache={job,events:events.events||[],artifacts:arts.artifacts||[]};renderDetail();tab(openTab||'summary')}catch(e){document.getElementById('summary').textContent='讀取工作明細失敗: '+e}}
function renderDetail(){if(!detailCache)return;const j=detailCache.job;document.getElementById('summary').innerHTML='<b>'+esc(j.job_id)+'</b><p>狀態：<span class="status '+esc(j.status)+'">'+esc(j.status)+'</span></p><p>Slot '+esc(j.agent_slot||'-')+' / PID '+esc(j.pid||'-')+'</p><p>開始：'+esc(showTime(j.started_at||j.accepted_at))+'<br>結束：'+esc(showTime(j.finished_at))+'</p><p>Workspace：'+esc(j.workspace_root||'')+'</p><p>stdout：'+esc(j.stdout_path||'')+'<br>stderr：'+esc(j.stderr_path||'')+'</p><pre>'+esc(JSON.stringify(j,null,2))+'</pre>';document.getElementById('events').textContent=JSON.stringify(detailCache.events,null,2);const a=detailCache.artifacts;document.getElementById('artifacts').innerHTML=a.length?a.map(x=>'<div class="artifact"><b>'+esc(x.relative_path||x.path)+'</b><div class="small">'+esc(x.kind)+' ｜ '+bytes(x.size)+' ｜ '+esc(showTime(x.modified_at))+(x.during_job_window?' ｜ 此工作時段':'')+'</div><div class="hash">SHA256 '+esc(x.sha256||'(大檔未計算)')+'</div><div class="small">'+esc(x.path)+'</div></div>').join(''):'<div class="small">這張工作目前沒有掃描到成果檔。</div>'}
function tab(name){for(const n of ['summary','events','artifacts']){document.getElementById(n).classList.toggle('hidden',n!==name);document.getElementById('t'+n[0].toUpperCase()+n.slice(1)).classList.toggle('active',n===name)}}
async function jobAction(kind){if(!selected){alert('請先選一張工作');return}if(kind==='cancel'&&!confirm('確定取消 '+selected+'？'))return;try{const r=await fetch('/v1/jobs/'+encodeURIComponent(selected)+'/'+kind,{method:'POST'}),body=await r.text();if(!r.ok)throw new Error('HTTP '+r.status+' '+body);await loadAll();await loadDetail(selected,'summary')}catch(e){alert(kind+' 失敗: '+e)}}
document.getElementById('filter').addEventListener('input',renderJobs);document.getElementById('status').addEventListener('change',renderJobs);setInterval(()=>{if(document.getElementById('auto').checked)loadAll()},3000);loadAll();
</script></body></html>`
