case_id=0005
machine=DESKTOP-ODAQN0D
requested_at=2026-08-18T22:43:30+08:00
transport=github-one-shot-bootstrap-only
business_execution=openworker-local-supervisor
publish_bootstrap_ack=true
reason=retry_after_preserving_openworker_failure_details_and_c_github_runner_probe
